# Generated by Django 4.2.7 on 2026-02-23 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Industria'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.plan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('INACTIVE', 'Inactiva')], default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('BASIC', 'Básico'), ('PRO', 'Pro'), ('CORPORATE', 'Corporativo'), ('ENTERPRISE', 'Empresa')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_active_projects',
            field=models.IntegerField(default=3, verbose_name='Máximo de Proyectos Activos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_docs',
            field=models.IntegerField(default=50, verbose_name='Máximo de Documentos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_storage_mb',
            field=models.IntegerField(default=1000, verbose_name='Máximo de Almacenamiento (MB)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_tickets_per_month',
            field=models.IntegerField(default=20, verbose_name='Máximo de Tickets/Mes'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(default=5, verbose_name='Máximo de Usuarios'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_clp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio (CLP)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='support_sla_hours',
            field=models.IntegerField(default=48, verbose_name='SLA de Soporte (horas)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Es Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Es Superusuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('STAFF_PM', 'Gestor de Proyectos'), ('STAFF_SUPPORT', 'Soporte'), ('CLIENT_ADMIN', 'Admin del Cliente'), ('CLIENT_USER', 'Usuario del Cliente')], default='CLIENT_USER', max_length=50, verbose_name='Rol'),
        ),
    ]
