# Generated by Django 5.1.5 on 2026-02-23 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('STAFF_PM', 'Gestor de Proyectos'), ('STAFF_SUPPORT', 'Soporte Técnico'), ('CLIENT_ADMIN', 'Admin del Cliente'), ('CLIENT_USER', 'Usuario del Cliente'), ('CLIENT_VIEWER', 'Espectador del Cliente')], max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_system', models.BooleanField(default=True, verbose_name='Es del Sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('AUTH', 'Autenticación'), ('COMPANIES', 'Empresas/Tenants'), ('USERS', 'Usuarios'), ('PROJECTS', 'Proyectos'), ('TASKS', 'Tareas/Kanban'), ('DOCUMENTS', 'Documentos'), ('TICKETS', 'Tickets/Soporte'), ('COMMENTS', 'Comentarios'), ('AUDIT', 'Auditoría'), ('SETTINGS', 'Configuración')], max_length=50, verbose_name='Módulo')),
                ('action', models.CharField(choices=[('VIEW', 'Ver'), ('CREATE', 'Crear'), ('EDIT', 'Editar'), ('DELETE', 'Eliminar'), ('EXPORT', 'Exportar'), ('ASSIGN', 'Asignar'), ('APPROVE', 'Aprobar'), ('DOWNLOAD', 'Descargar')], max_length=50, verbose_name='Acción')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permissions',
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.permission', verbose_name='Permiso')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_set', to='companies.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Rol',
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
