# Generated by Django 4.2.7 on 2026-03-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_role_permission_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Solo visible para staff'),
        ),
    ]
